[package]
name = "tuicker"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version="0.29.0", features=["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
reqwest = "0.12.23"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version="1.47.1", features=["full"] }
